### ISSUE TITLE
Copy Hex Value when Clicked

### ISSUE THREAD

**Issue by etleyden** [etleyden/react-color-picker#3]
I would like to add the feature to copy the hex code whenever the user clicks on it. An additional feature to go with this is a tooltip to indicate that the color has been copied to the clipboard.

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by etleyden** [comment]
@IrfanSalim It's all yours!

**Comment by Farzzn** [comment]
I completed it issue, please check my pr

https://github.com/etleyden/react-color-picker/assets/90022626/1ed7076e-9ebc-41c0-99f6-3945d467089c

**Comment by etleyden** [comment]
Thanks @Farzzn! Merged and closing issue.
